django_classified/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LogoutView
from django.contrib.sitemaps.views import sitemap as sitemap_view
from django.views.decorators.cache import cache_page, never_cache

from . import views, feeds, sitemap

app_name = 'django_classified'

urlpatterns = [
    url(r'^$', views.SectionListView.as_view(), name='index'),
    url(r'^new/$', never_cache(views.ItemCreateView.as_view()), name='item-new'),
    url(r'^edit/(?P<pk>\d+)/$', never_cache(views.ItemUpdateView.as_view()), name='item-edit'),
    url(r'^(?P<pk>\d+)-(?P<slug>[-\w]+)/$', views.ItemDetailView.as_view(), name='item'),
    url(r'^group/(?P<pk>\d+)-(?P<slug>[-\w]+)/$', views.GroupDetail.as_view(), name='group'),
    url(r'^search/', views.SearchView.as_view(), name='search'),
    url(r'^robots\.txt$', cache_page(60 * 60)(views.RobotsView.as_view()), name='robots'),
    url(r'^sitemap\.xml$', sitemap_view, {'sitemaps': sitemap.sitemaps_dict}, name='sitemap'),
    url(r'^rss\.xml$', cache_page(60 * 15)(feeds.LatestItemFeed()), name='rss'),
    url(r'^user/$', views.MyItemsView.as_view(), name='user-items'),
    url(r'^user/profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^user/my/delete/(?P<pk>\d+)/$', views.ItemDeleteView.as_view(), name='my-delete'),
    url(r'^user/logout/$', LogoutView.as_view(), name='logout'),
    url(r'^user/set-area/$', views.SetAreaView.as_view(), name='set-area'),
]

project/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.urls import path

from django_classified.views import area_upload

urlpatterns = [
    path('', include('django_classified.urls', namespace='django_classified')),
    path('social/', include('social_django.urls', namespace='social')),
    path('admin/', admin.site.urls),

    # Create custom login page using default 'registration/login.html' template path
    path('login/', auth_views.LoginView.as_view(template_name='demo/login.html'), name='login'),
    path('email-sent/', TemplateView.as_view(template_name='demo/email_sent.html')),
    path('upload-csv/', area_upload, name="area_upload"),
]

django_classified/models.py
from django.conf import settings
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils.functional import cached_property
from django.utils.translation import ugettext as _
from sorl.thumbnail import ImageField
from unidecode import unidecode
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib.auth.models import User

from . import settings as dcf_settings


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    email = models.CharField(_('Contact email'), max_length=50, null=True, blank=True)
    phone = models.CharField(_('Contact phone'), max_length=50, null=True, blank=True)
    receive_news = models.BooleanField(_('receive news'), default=True, db_index=True)

    def allow_add_item(self):
        return self.user.item_set.count() < dcf_settings.ITEM_PER_USER_LIMIT

    @staticmethod
    def get_or_create_for_user(user):
        if hasattr(user, 'profile'):
            return user.profile
        else:
            return Profile.objects.create(user=user)


class Area(models.Model):
    slug = models.SlugField()
    state = models.CharField(_('state'), max_length=100, default='State')
    county = models.CharField(_('county'), max_length=100, default='County')
    city = models.CharField(_('city'), max_length=100, default='City')

    
    
    def __str__(self):
        return self.state

    class Meta:
        ordering = ('state',)
        verbose_name = _('area')
        verbose_name_plural = _('areas')

    @classmethod
    def get_for_request(cls, request):
        if 'area_pk' in request.session:
            try:
                return cls.objects.get(pk=request.session['area_pk'])
            except cls.DoesNotExist:
                return None
        return None

    def set_for_request(self, request):
        request.session['area_pk'] = self.pk

    @classmethod
    def delete_for_request(cls, request):
        if 'area_pk' in request.session:
            del request.session['area_pk']


class Section(models.Model):
    title = models.CharField(_('title'), max_length=100)

    def __str__(self):
        return self.title

    @cached_property
    def count(self):
        return Item.objects \
            .filter(is_active=True) \
            .filter(group__section=self) \
            .count()

    class Meta:
        verbose_name = _('section')
        verbose_name_plural = _('sections')


class Group(models.Model):
    slug = models.SlugField(blank=True, null=True)
    title = models.CharField(_('title'), max_length=100)
    section = models.ForeignKey('Section', verbose_name=_('section'), on_delete=models.CASCADE)

    def __str__(self):
        return '%s - %s' % (self.section.title, self.title)

    @cached_property
    def count(self):
        return self.item_set.filter(is_active=True).count()

    class Meta:
        verbose_name = _('group')
        verbose_name_plural = _('groups')
        ordering = ['section__title', 'title', ]

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.title))
        super(Group, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('django_classified:group', kwargs={'pk': self.pk, 'slug': self.slug})


class ActiveManager(models.Manager):
    def get_queryset(self):
        return super(ActiveManager, self).get_queryset().filter(is_active=True)


class Item(models.Model):
    slug = models.SlugField(blank=True, null=True, max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, verbose_name=_('group'), on_delete=models.CASCADE)
    area = models.ForeignKey(Area, verbose_name=_('area'), on_delete=models.CASCADE, null=True, blank=True)
    state = models.CharField(_('state'), max_length=100)
    county = models.CharField(_('county'), max_length=100)
    city = models.CharField(_('city'), max_length=100)
    title = models.CharField(_('title'), max_length=100)
    description = models.TextField(_('description'))
    price = models.DecimalField(_('price'), max_digits=10, decimal_places=2)
    is_active = models.BooleanField(_('active'), default=True, db_index=True)
    updated = models.DateTimeField(_('updated'), auto_now=True, db_index=True)
    posted = models.DateTimeField(_('posted'), auto_now_add=True)

    objects = models.Manager()
    active = ActiveManager()

    def __str__(self):
        if not self.is_active:
            return '[%s] %s' % (_('in active'), self.title)
        else:
            return self.title

    class Meta:
        verbose_name = _('item')
        verbose_name_plural = _('items')
        ordering = ('-updated', )

    def get_absolute_url(self):
        return reverse('django_classified:item', kwargs={
            'pk': self.pk,
            'slug': self.slug
        })

    @cached_property
    def get_keywords(self):
        return ",".join(set(self.description.split()))

    @cached_property
    def contact_phone(self):
        return self.user.profile.phone

    @cached_property
    def image_count(self):
        return self.image_set.count()

    @cached_property
    def featured_image(self):
        return self.image_set.all().first()

    @cached_property
    def related_items(self):
        qs = Item.objects \
            .filter(is_active=True) \
            .filter(group=self.group) \
            .exclude(pk=self.pk)

        return qs[:dcf_settings.RELATED_LIMIT]

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.title))
        super(Item, self).save(*args, **kwargs)


class Image(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    file = ImageField(_('image'), upload_to='images')

django_classified/forms.py
from django import forms
from django.utils.translation import ugettext as _
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Item, Group, Profile, Area, Section


class SearchForm(forms.Form):
    group = forms.ModelChoiceField(label=_('Group'), queryset=Group.objects.all(), required=False)
    area = forms.ModelChoiceField(label=_('Choose State'), queryset=Area.objects.values_list('state', flat=True).distinct(), required=True)
    county = forms.CharField(required=True, label=_('Enter County'))
    city = forms.CharField(required=True, label=_('Enter City'))
    q = forms.CharField(required=False, label=_('Description'))
    
    def filter_by(self):
        # TODO search using more than one field
        # TODO split query string and make seaprate search by words
        filters = {}
        if self.cleaned_data['group']:
            filters['group'] = self.cleaned_data['group']

        if self.cleaned_data['area']:
            filters['area'] = self.cleaned_data['area']

        filters['description__icontains'] = self.cleaned_data['q']

        return filters
    
class CreateForm(forms.ModelForm):
    typeOfListing = forms.ModelChoiceField(label=_('1. Type of Listing'), queryset=Section.objects.values_list('title', flat=True))
    statelist = forms.ModelChoiceField(label=_('2. Choose State'), queryset=Area.objects.values_list('state', flat=True).distinct(), required=True)
    county = forms.CharField(required=True, label=_('2a. Enter County'))
    city = forms.CharField(required=True, label=_('2b. Enter City'))
    contractorsList = forms.ModelChoiceField(label=_('3. Contractor by Trade'), queryset=Group.objects.filter(section_id=1).values_list('title', flat=True))
    workersList = forms.ModelChoiceField(label=_('3a. Worker by Trade'), queryset=Group.objects.filter(section_id=2).values_list('title', flat=True))
    architectList = forms.ModelChoiceField(label=_('3b. Type of Architect'), queryset=Group.objects.filter(section_id=3).values_list('title', flat=True))
    engineerList = forms.ModelChoiceField(label=_('3c. Type of Engineer'), queryset=Group.objects.filter(section_id=4).values_list('title', flat=True))

    class Meta:
        model = Item
        fields = (
            'title',
            'description',
            'price',
            'is_active'
        )

    def filter_by(self):
        # TODO search using more than one field
        # TODO split query string and make seaprate search by words
        filters = {}
        if self.cleaned_data['group']:
            filters['group'] = self.cleaned_data['group']

        if self.cleaned_data['area']:
            filters['area'] = self.cleaned_data['area']

        filters['description__icontains'] = self.cleaned_data['q']

        return filters


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = (
            'area',
            'group',
            'state',
            'county',
            'city',
            'description',
            'price',
            'is_active'
        )

        
class EmailWidget(forms.TextInput):
    input_type = 'email'

class PhoneWidget(forms.TextInput):
    input_type = 'phone'

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = (
            'email',
            'phone',
        )
        widgets = {
            'email': EmailWidget,
            'phone': PhoneWidget
        }

class SignUpForm(UserCreationForm):
    class Meta:
        model = Profile
        fields = (
            'phone',
        )
        widgets = {
            'phone': PhoneWidget
        }

django_classified/templates/django_classified/_base.html
{% spaceless %}

  {% load static i18n %}

  <!DOCTYPE HTML>
  <html lang="en">

  <head>
    <title>{% block title %}{% endblock title %} | {{ DCF.SITE_NAME }}</title>

    <meta name="description"
          content="{% block meta_description %}{{ DCF.SITE_DESCRIPTION }}{% endblock meta_description %}"/>
    <meta name="keywords" content="{% block meta_keywords %}{% endblock meta_keywords %}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if GOOGLE_SITE_VERIFICATION_ID %}
      <meta name="google-site-verification" content="{{ GOOGLE_SITE_VERIFICATION_ID }}"/>
    {% endif %}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    {% if FACEBOOK_APP_ID %}
      <meta property="fb:app_id" content="{{ FACEBOOK_APP_ID }}"/>
    {% endif %}
    <meta property="og:type" content="website"/>
    {% block meta_og %}{% endblock %}

    <link rel="icon" type="image/x-icon" href="{% static 'django_classified/images/favicon.ico' %}"/>

    <link href="{% static 'django_classified/css/bootstrap.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'django_classified/css/jumbotron-narrow.css' %}" rel="stylesheet"/>
    <link href="{% static 'django_classified/css/lightbox.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'django_classified/css/style.css' %}" rel="stylesheet" type="text/css"/>

    <link rel="alternate" type="application/rss+xml" href="{% url 'django_classified:rss' %}">

  </head>

  <body>
  <div class="container">

    <div class="header clearfix">
      <nav>
        <ul class="nav nav-pills pull-right">
          <li role="presentation" class="active"><a
                  href="{% url 'django_classified:item-new' %}">{% trans "Create a Listing" %}</a>
          </li>
          <li role="presentation"><a href="{% url 'django_classified:index' %}">{% trans "Home" %}</a></li>
          <li role="presentation"><a href="{% url 'django_classified:search' %}">{% trans "Search" %}</a></li>
          {% if user.is_authenticated %}
            <li role="presentation" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <span class="glyphicon glyphicon-user"></span> {{ user.username }} <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'django_classified:user-items' %}">{% trans "My items" %} ({{ user.item_set.count }})</a>
                </li>
                <li>
                  <a href="{% url 'django_classified:profile' %}">{% trans "Profile" %}</a>
                </li>
                <li class="divider"></li>
                <li><a href="{% url 'django_classified:logout' %}?next=/">{% trans "Logout" %}</a></li>
              </ul>
            </li>
          {% else %}
            <li role="presentation">
              <a href="{% url 'django_classified:profile' %}" title="{% trans "Login" %}">
                <span class="glyphicon glyphicon-user"></span> {% trans "Login/Register" %}
              </a>
            </li>
          {% endif %}
        </ul>
      </nav>
      <h4 class="text-muted"><a href="{% url 'django_classified:index' %}">{{ DCF.SITE_NAME }}</a>
        <!-- {% if area_list %}
          &nbsp;
          <small>
            <select id="area-selector">
              <option value="">{% trans 'All areas' %}</option>
              {% for area_item in area_list %}
                <option value="{{ area_item.state }}" {% if area.pk == area_item.pk %}selected{% endif %}>
                  {{ area_item }}
                </option>
              {% endfor %}
            </select>
          </small>
        {% endif %} -->
      </h4>
    </div>

    {% if messages %}
      {% for message in messages %}
        <div class='row'>
          <div class="col-md-12">
            <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
              <button type="button" class="close" data-dismiss="alert">×</button>
              {{ message|safe }}
            </div>
          </div>
        </div>
      {% endfor %}
    {% endif %}

    {% block body %}

    {% endblock %}

    <footer class="footer">
      <span class="pull-left">{{ DCF.SITE_NAME }}</span>
      {% if DCF.DISPLAY_CREDITS %}
        <span class="pull-right">{% trans "Powered by" %} <a>Django Classified Ads</a></span>
      {% endif %}
    </footer>

  </div>

  <script src="{% static 'django_classified/js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'django_classified/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'django_classified/js/lightbox.min.js' %}"></script>

  {% block ext_scripts %}{% endblock %}

  {% if GOOGLE_ANALYTICS_PROPERTY_ID %}
    <script>
      (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
          (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
        a = s.createElement(o),
            m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
      })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

      ga('create', '{{ GOOGLE_ANALYTICS_PROPERTY_ID }}', 'auto');
      ga('send', 'pageview');
    </script>
  {% endif %}

  <script>
    $(function () {
      $('#area-selector').on('change', function () {
        var params = {
          area_slug: this.value,
          next: window.location.href
        };
        window.location = "{% url 'django_classified:set-area' %}?" + $.param(params);
      });
    });
  </script>

  <!-- generated {% now "jS F Y H:i:s" %} -->
  </body>
  </html>
{% endspaceless %}

django_classified/templates/django_classified/admin_toolbar.inc.html
{% load i18n %}

{% if user.is_superuser %}
  <div class="row">
    <div class="col-lg-12">
      <a href='{% url 'django_classified:my-delete' item.pk %}' class="btn btn-danger">
        {% trans "Delete" %}
      </a>
      <a href='{% url 'django_classified:item-edit' item.pk %}' class="btn btn-default">
        {% trans "Edit" %}
      </a>
    </div>
  </div>
{% endif %}

django_classified/templates/django_classified/form_pagination.inc.html
{% load i18n %}

<nav>
  <ul class="pagination">
    <li>
      <button class="btn btn-default"
              name="page"
              value="{% if page_obj.has_previous %}{{ page_obj.previous_page_number }}{% endif %}"
              type="submit"
              {% if not page_obj.has_previous %}
              disabled="disabled"
              {% endif %}>
        {% trans "Prev" %}
      </button>
    </li>

    <li>
      <button class="btn btn-default"
              name="page"
              value="{% if page_obj.has_next %}{{ page_obj.next_page_number }}{% endif %}"
              type="submit"
              {% if not page_obj.has_next %}
              disabled="disabled"
              {% endif %}>
        {% trans "Next" %}
      </button>
    </li>
  </ul>
</nav>

django_classified/templates/django_classified/item_detail.html
{% extends "django_classified/_base.html" %}

{% load classified %}
{% load humanize %}
{% load i18n %}
{% load thumbnail %}

{% block title %}{{ object.title }}{% endblock title %}
{% block meta_description %}{{ object.description }}{% endblock meta_description %}
{% block meta_keywords %}{{ object.get_keywords }}{% endblock meta_keywords %}

{% block meta_og %}
  <meta property="og:url" content="{{ request.scheme }}://{{ request.get_host }}{{ object.get_absolute_url }}"/>
  <meta property="og:title" content="{{ object.title }}"/>
  <meta property="og:description" content="{{ object.description }}"/>
  {% for img in object.image_set.all %}
    {% thumbnail img.file "x800" as im %}
      <meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{{ im.url }}"/>
      <meta property="og:image:alt" content="{{ object.title }}"/>
    {% endthumbnail %}
  {% endfor %}
{% endblock %}

{% block body %}

  <div itemscope itemtype="http://schema.org/Product">

    <div class="row">
      <div class="col-md-12">
        <h3>
          {% if object.area %}
            {{ object.area }}&nbsp;&gt;&nbsp;
          {% endif %}
          <a href='{{ object.group.get_absolute_url }}'>{{ object.group }}</a>
        </h3>
      </div>
    </div>

    {% include "django_classified/admin_toolbar.inc.html" %}

    <div class="row">
      <div class="col-lg-9">
        <h2 itemprop="name">{{ object.title }}</h2>
      </div>
      <div class="col-lg-3">
                <span itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                <meta itemprop="priceCurrency" content="{{ DCF.CURRENCY }}"/>
                <h2 itemprop="price" content="{{ object.price|floatformat }}">{{ object.price|currency }}</h2>
                </span>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12" itemprop="description">
        {{ object.description|linebreaks }}
      </div>
    </div>

    {% if object.image_count %}
      <div class="row">
        <div class="col-lg-12">
          {% for img in object.image_set.all %}
            {% thumbnail img.file "150x150" crop="center" as im %}
              <a href='{{ img.file.url }}' data-lightbox="lightbox[{{ object.id }}]"
                 title="{{ object.title }}">
                <img itemprop="image" src='{{ im.url }}' alt='{{ object.title }}' title='{{ object.title }}'
                     width="{{ im.width }}" height="{{ im.height }}" class="img-rounded"/>
              </a>
            {% endthumbnail %}
          {% endfor %}
        </div>
      </div>
    {% endif %}

    <div class="row">
      <div class="col-lg-12">
        <small>{% trans 'Posted' %}: {{ object.posted|timesince }} ago</small>
      </div>
    </div>
  </div>

  {% if object.contact_phone %}
    <div class="row">
      <div class="col-md-12">
        <hr/>
        {% if DCF.LOGIN_TO_CONTACT and not user.is_authenticated %}
          {% trans "Please" %} <a href='{% url 'django_classified:profile' %}'>{% trans "login" %}</a>
          {% trans "to see contact information." %}
        {% else %}
          {% trans "Contact phone" %}: {{ object.contact_phone }}
        {% endif %}
      </div>
    </div>
  {% endif %}

  <div class="row">
    {% for item in object.related_items %}
      {% if forloop.first %}
        <hr/>
      {% endif %}
      <div class="col-md-2">
        {% if item.featured_image %}
          {% thumbnail featured_image.file "70x70" crop="center" as im %}
            <a href='{{ item.get_absolute_url }}' title="{{ item.title }}">
              <img
                      src='{{ im.url }}'
                      alt='{{ item.title }}'
                      title='{{ item.title }}'
                      width="{{ im.width }}"
                      height="{{ im.height }}"
                      class="img-rounded"
              />
            </a>
          {% endthumbnail %}
          <br/>
        {% endif %}
        <a href='{{ item.get_absolute_url }}' title="{{ item.title }}">{{ item.title|truncatewords:3 }}</a>
      </div>
    {% endfor %}
  </div>
{% endblock %}

django_classified/templates/django_classified/item_list.html
{% extends "django_classified/_base.html" %}

{% block title %}{{ object }}{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-lg-12">
      <h4>
        <a href="{% url 'django_classified:index' %}#{{ object.section.id }}">{{ object.section }}</a> > <a
              href="{{ object.get_absolute_url }}" title="{{ object.title }}">
          {{ object.title }}
        </a>
      </h4>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      {% include "django_classified/item_list.inc.html" %}
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      {% include "django_classified/list_pagination.inc.html" %}
    </div>
  </div>
{% endblock body %}

django_classified/templates/django_classified/item_list.inc.html
{% load classified %}
{% load humanize %}
{% load i18n %}
{% load thumbnail %}

{% for object in object_list %}
  {% if forloop.first %}
    <table class="table table-hover">
    <thead>
    <tr>
      <td></td>
      <td>{% trans "Price" %}</td>
    </tr>
    </thead>
    <tbody>
  {% endif %}
<tr>
  <td>
    {% if object.featured_image %}
      {% thumbnail object.featured_image.file "45x45" crop="center" as im %}
        <a href='{{ object.get_absolute_url }}' title="{{ object.title }}">
          <img
                  src='{{ im.url }}'
                  alt='{{ object.title }}'
                  title='{{ object.title }}'
                  width="{{ im.width }}"
                  height="{{ im.height }}"
                  class="img-rounded"
          />
          {% if object.image_count > 1 %}
            <span class="badge badge-notify"
                  title="{{ object.image_count|add:-1 }} {% trans 'more photos available' %}"> + {{ object.image_count|add:-1 }}</span>
          {% endif %}
        </a>
      {% endthumbnail %}
    {% endif %}
    <a href='{{ object.get_absolute_url }}' title='{{ object.title }}'>
      {{ object.title }}
    </a>
  </td>
  <td>
    {{ object.price|currency }}
  </td>
</tr>
{% if forloop.last %}
  </tbody>
  </table>
{% endif %}

{% empty %}
  <p>
    {% trans "No item here yet." %}
    <a href="{% url 'django_classified:item-new' %}" class="btn btn-default">{% trans "Add one now!" %}</a>
  </p>
{% endfor %}

django_classified/templates/django_classified/list_pagination.inc.html
{% load i18n %}

<nav>
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li>
        <a href="?page={{ page_obj.previous_page_number }}">{% trans "Prev" %}</a>
      </li>
    {% endif %}
    {% if page_obj.has_next %}
      <li>
        <a href="?page={{ page_obj.next_page_number }}">{% trans "Next" %}</a>
      </li>
    {% endif %}
  </ul>
</nav>

django_classified/templates/django_classified/search.html
{% extends "django_classified/_base.html" %}

{% load i18n bootstrap %}

{% block title %}
  {% if form.q.value %}{% trans "Search results for query" %} "{{ form.q.value }}" {% else %}
    {% trans "Search" %}{% endif %}
{% endblock title %}

{% block body %}
  <div class="row">
    <div class="col-lg-6">
      <h3>{% trans "Search" %}</h3>
      <form method="get" role="form">
        {{ form|bootstrap }}
        <button type="submit" class="btn btn-default" name="page" value="1">{% trans "Search" %}</button>
        {% if object_list|length %}
          {% include 'django_classified/form_pagination.inc.html' %}
        {% endif %}
      </form>
    </div>
  </div>
  <div>
    <hr/>
    {% if object_list|length %}
      <h4>{% blocktrans with count=page_obj.paginator.count %}Search results ({{ count }} items
        found):{% endblocktrans %}</h4>
      {% include "django_classified/item_list.inc.html" with item=object %}
    {% else %}
      <h4>{% trans "Not found" %}</h4>
    {% endif %}
  </div>
{% endblock %}

django_classified/templates/django_classified/user_item_list.html
{% extends "django_classified/_base.html" %}

{% load humanize i18n %}

{% block title %}{% trans "My items" %}{% endblock title %}

{% block body %}
  <div class="row">
    <div class="col-lg-12">
      <h2>{% trans "My items" %}</h2>
      {% for object in object_list %}
        {% if forloop.first %}
          <table class="table table-striped table-hover">
          <thead>
          <tr>
            <td>{% trans "Group" %}</td>
            <td>{% trans "Title" %}</td>
            <td>{% trans "Price" %}</td>
            <td>{% trans "Posted" %}</td>
            <td>{% trans "Active" %}</td>
            <td>{% trans "Edit" %}</td>
            <td>{% trans "Delete" %}</td>
          </tr>
          </thead>
        {% endif %}
      <tr>
        <td><a href='{{ object.group.get_absolute_url }}'>{{ object.group }}</a></td>
        <td><a href='{{ object.get_absolute_url }}' title='{% trans "Open item" %}'>{{ object }}</a></td>
        <td>{{ object.price|intcomma }}</td>
        <td>{{ object.posted|timesince }}</td>
        <td>{{ object.is_active|yesno }}</td>
        <td>
          <a
                  href='{% url 'django_classified:item-edit' object.pk %}'
                  title='{% trans "Edit item" %}'
                  class="btn btn-default">
            {% trans "Edit" %}
          </a>
        </td>
        <td>
          <a href='{% url 'django_classified:my-delete' object.id %}' class="btn btn-danger">
            {% trans "Delete" %}
          </a>
        </td>
      </tr>

      {% if forloop.last %}
        </table>
      {% endif %}

      {% empty %}
        <p>
          {% trans "You have no items to show." %}
          <a href="{% url 'django_classified:item-new' %}">{% trans "Add one now!" %}</a>
        </p>
      {% endfor %}
    </div>
  </div>
{% endblock %}